apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: sam-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sam-frontend
        image: bekube/sam-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
